/**
 * Syncs contract deployments and ABIs from the Foundry workspace into the web app.
 *
 *   bun run sync
 *
 * Inputs (read-only):
 *   contracts/deployments/{196,1952}.json
 *   contracts/out/<File>.sol/<Name>.json   (Foundry artifacts, `abi` field)
 *
 * Outputs (committed):
 *   src/generated/deployments.json
 *   src/generated/abis.ts
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(webRoot, "..");
const outDir = join(repoRoot, "contracts", "out");
const deploymentsDir = join(repoRoot, "contracts", "deployments");
const generatedDir = join(webRoot, "src", "generated");

const CHAIN_IDS = [196, 1952] as const;

/** [exportName, artifactFile, contractName] */
const ARTIFACTS: Array<[string, string, string]> = [
  ["launchFactoryAbi", "LaunchFactory.sol", "LaunchFactory"],
  ["bondingCurveAbi", "BondingCurve.sol", "BondingCurve"],
  ["templateRegistryAbi", "TemplateRegistry.sol", "TemplateRegistry"],
  ["perkComposableHookV1Abi", "PerkComposableHookV1.sol", "PerkComposableHookV1"],
  ["graduationManagerAbi", "GraduationManager.sol", "GraduationManager"],
  ["feeRouterAbi", "FeeRouter.sol", "FeeRouter"],
  ["holderRewardDistributorAbi", "HolderRewardDistributor.sol", "HolderRewardDistributor"],
  ["lpGrantVaultAbi", "LPGrantVault.sol", "LPGrantVault"],
  ["referralRegistryAbi", "ReferralRegistry.sol", "ReferralRegistry"],
  ["perkMemeTokenAbi", "PerkMemeToken.sol", "PerkMemeToken"],
  ["assetRegistryAbi", "AssetRegistry.sol", "AssetRegistry"],
  ["poolSwapTestAbi", "PoolSwapTest.sol", "PoolSwapTest"], // lib/v4-core test router artifact
];

function readJson(path: string): unknown {
  return JSON.parse(readFileSync(path, "utf8"));
}

function main(): void {
  mkdirSync(generatedDir, { recursive: true });

  // ---- deployments ----
  const deployments: Record<string, unknown> = {};
  for (const chainId of CHAIN_IDS) {
    const path = join(deploymentsDir, `${chainId}.json`);
    if (!existsSync(path)) {
      console.warn(`warn: deployments/${chainId}.json not found, writing null`);
      deployments[String(chainId)] = null;
      continue;
    }
    deployments[String(chainId)] = readJson(path);
    console.log(`deployments/${chainId}.json -> chainId ${chainId}`);
  }
  const deploymentsPath = join(generatedDir, "deployments.json");
  writeFileSync(deploymentsPath, JSON.stringify(deployments, null, 2) + "\n");
  console.log(`wrote ${deploymentsPath}`);

  // ---- ABIs ----
  const chunks: string[] = [
    "// GENERATED by scripts/sync-contracts.ts — do not edit by hand. Run `bun run sync`.",
    "",
  ];
  for (const [exportName, file, name] of ARTIFACTS) {
    const artifactPath = join(outDir, file, `${name}.json`);
    if (!existsSync(artifactPath)) {
      throw new Error(`artifact not found: contracts/out/${file}/${name}.json (run forge build first)`);
    }
    const artifact = readJson(artifactPath) as { abi?: unknown };
    if (!artifact.abi) throw new Error(`no abi in ${artifactPath}`);
    chunks.push(`export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;`);
    chunks.push("");
    console.log(`abi ${name} <- contracts/out/${file}/${name}.json`);
  }
  const abisPath = join(generatedDir, "abis.ts");
  writeFileSync(abisPath, chunks.join("\n"));
  console.log(`wrote ${abisPath}`);
}

main();
